### ISSUE TITLE
Multiple keybinds?

### ISSUE THREAD

**Issue by AstraLuma** [glyph/QuickMacHotKey#3]
Based on the given example in the README:

```
from quickmachotkey import quickHotKey, mask
from quickmachotkey.constants import kVK_ANSI_O, kVK_F18, cmdKey, controlKey, optionKey, shiftKey


@quickHotKey(virtualKey=kVK_F18, modifierMask=mask())
def handle_pause() -> None:
    print("pause music")


@quickHotKey(virtualKey=kVK_ANSI_O, modifierMask=mask(cmdKey, controlKey, optionKey, shiftKey))
def handle_play() -> None:
    print("play music")


def main():
    from AppKit import NSApplication  # type:ignore[import]
    from PyObjCTools import AppHelper  # type:ignore[import]
    NSApplication.sharedApplication()
    AppHelper.runEventLoop()
```

Both keys are handled, but the second handler is called in both cases.

**Comment by AstraLuma** [comment]
This reads like python variable scoping confusion (eg, like when you mix loops and closures), but looking at your source, I don't see how.

**Comment by AstraLuma** [comment]
Went to town with `print()`, two things have caught my eye:

* Both calls to `InstallEventHandler` are returning the same value to `handlerRef` (`(0, ())`)
* The same instance of `handlerShim` is being called by both events

Current theory is that `InstallEventHandler` is being called such that it's replacing/updating the previous installation?

**Comment by AstraLuma** [comment]
OH that is exactly what is happening.

`InstallEventHandler` is passed a ` spec` of basically "some hot key is pressed", so all hot keys are funneled through the same event, and it's up to the callback (`handlerShim`) to determine which one and dispatch appropriately.

Gonna toss https://web.archive.org/web/20070116050535/http://dbachrach.com/blog/2005/11/program-global-hotkeys-in-cocoa-easily/ on to the link pile.

Fixing this so that multiple hot keys work seems like a big enough refactor that I don't want to just blindly submit a PR for it.

**Comment by amastis** [comment]
@AstraLuma Did you ever figure out a solution to having multiple hotkeys in a file?

**Comment by glyph** [comment]
I thought maybe the last release had fixed it, but it actually makes things worse (only the latter handler is called).

I thought the documentation for this stuff had been scrubbed clean off the internet, but apple does still host it in their "documentation archive", https://developer.apple.com/library/archive/documentation/Carbon/Conceptual/Carbon_Event_Manager/Concept/CarbonEventsConcept.html#//apple_ref/doc/uid/TP30000989-CH202-BABCHCHA

**Comment by glyph** [comment]
OK, I've totally misunderstood how these APIs are supposed to be used.

*Event handlers* stack, and are meant to be a way to organize different elements of your application.  Like a click handler on a window vs. the click handler on a particular button within that window.  If the button doesn't handle it, the window does.  We have a single handler here, there's no reason for events to cascade; we just want to dispatch to our own separate hotkeys here.  This is where the function pointer lives.

*Event targets* are just a small, fixed set of things, so we can't make a new one, `GetEventDispatcherTarget()` is kind of our only choice.

*Event parameters* are the missing piece here.  Unlike most modern macOS APIs, where you pass along a bit of state that is relayed to you as a `void*` or similar on every callback as a parameter, event parameters are global state that is accessed via `GetEventParameter`.  `inHotKeyID` is documented as:

```
 *    inHotKeyID:
 *      The application-specified hot key ID. You will receive this in
 *      the kEventHotKeyPressed event as the direct object parameter.
```

The way you get the "direct object parameter" is

```
GetEventParameter (event, kEventParamDirectObject,
                    typeHICommand, NULL, sizeof(HICommand),
                    NULL, &commandStruct);
```

Let me see if I can fix that

**Comment by glyph** [comment]
Psst @amastis it's fixed
