### ISSUE TITLE
when focused on other app throughs error

### ISSUE THREAD

**Issue by Alvin-Alford** [glyph/QuickMacHotKey#8]
type ⌘⌃⌥X with any application focused
handled ⌘⌃⌥X
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSViewBackingLayer NS_setView:]: unrecognized selector sent to instance 0x101b84790'
*** First throw call stack:
(
        0   CoreFoundation                      0x0000000193c98050 __exceptionPreprocess + 176
        1   libobjc.A.dylib                     0x000000019377ecd8 objc_exception_throw + 88
        2   CoreFoundation                      0x0000000193d4d364 -[NSObject(NSObject) __retain_OA] + 0
        3   CoreFoundation                      0x0000000193c04b70 ___forwarding___ + 1568
        4   CoreFoundation                      0x0000000193c04490 _CF_forwarding_prep_0 + 96
        5   AppKit                              0x0000000197784468 -[NSView setLayer:] + 340
        6   AppKit                              0x0000000198212510 -[NSView _createLayerAndInitialize] + 156
        7   AppKit                              0x00000001977836a0 -[NSView _updateLayerBackedness] + 556
        8   AppKit                              0x00000001977833e4 -[NSView didChangeValueForKey:] + 56
        9   AppKit                              0x00000001984aa564 -[NSMenuBarImpl _newMenuBarStackViewWithAppearance:] + 456
        10  AppKit                              0x00000001984a9944 -[NSMenuBarImpl ensureRepresentationViewForDisplayID:] + 156
        11  AppKit                              0x000000019858d16c -[NSMenuBarLocalDisplayWindow _reconfigDisplay] + 64
        12  AppKit                              0x000000019858c450 -[NSMenuBarLocalDisplayWindow initWithImpl:display:frame:aperture:] + 204
        13  AppKit                              0x000000019858bce0 +[NSMenuBarDisplayWindow windowWithImpl:display:frame:aperture:] + 160
        14  AppKit                              0x00000001984952e8 -[NSMenuBarWindowManager _createWindowForDisplay:withImpl:] + 348
        15  AppKit                              0x00000001984950d8 -[NSMenuBarWindowManager windowOnDisplay:creatingIfNeeded:withImpl:] + 168
        16  AppKit                              0x000000019849b524 __60-[NSMenuBarPresentationInstance _forEachWindowDo:withBlock:]_block_invoke + 128
        17  AppKit                              0x000000019849b2e0 -[NSMenuBarPresentationInstance _forEachWindowDo:withBlock:] + 348
        18  AppKit                              0x0000000198497acc -[NSMenuBarPresentationInstance _setBoundsAndUpdateResolution] + 124
        19  AppKit                              0x000000019849451c _NSMenuBarDisplayManagerActiveSpaceChanged + 44
        20  SkyLight                            0x00000001996dedd0 _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 932
        21  SkyLight                            0x0000000199adfb68 _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 228
        22  SkyLight                            0x0000000199adfa64 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 28
        23  libdispatch.dylib                   0x000000019398a8f8 _dispatch_call_block_and_release + 32
        24  libdispatch.dylib                   0x000000019398c658 _dispatch_client_callout + 20
        25  libdispatch.dylib                   0x000000019399af68 _dispatch_main_queue_drain + 980
        26  libdispatch.dylib                   0x000000019399ab84 _dispatch_main_queue_callback_4CF + 44
        27  CoreFoundation                      0x0000000193c64bb4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
        28  CoreFoundation                      0x0000000193c24930 __CFRunLoopRun + 1996
        29  CoreFoundation                      0x0000000193c23ae8 CFRunLoopRunSpecific + 572
        30  HIToolbox                           0x000000019f1980cc RunCurrentEventLoopInMode + 292
        31  HIToolbox                           0x000000019f19debc ReceiveNextEventCommon + 636
        32  HIToolbox                           0x000000019f19e020 _BlockUntilNextEventMatchingListInModeWithFilter + 76
        33  AppKit                              0x000000019776b0f4 _DPSNextEvent + 660
        34  AppKit                              0x000000019809b690 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
        35  AppKit                              0x000000019775e200 -[NSApplication run] + 480
        36  libffi.dylib                        0x00000001a5f4e050 ffi_call_SYSV + 80
        37  libffi.dylib                        0x00000001a5f56b04 ffi_call_int + 1208
        38  _objc.cpython-310-darwin.so         0x00000001010737c0 PyObjCFFI_Caller + 2548
        39  _objc.cpython-310-darwin.so         0x00000001010ae6b4 objcsel_vectorcall + 1260
        40  Python                              0x0000000101536068 call_function + 132
        41  Python                              0x000000010152ea4c _PyEval_EvalFrameDefault + 23476
        42  Python                              0x000000010152767c _PyEval_Vector + 360
        43  Python                              0x0000000101536068 call_function + 132
        44  Python                              0x000000010152ea4c _PyEval_EvalFrameDefault + 23476
        45  Python                              0x000000010152767c _PyEval_Vector + 360
        46  Python                              0x0000000101590b50 pyrun_file + 308
        47  Python                              0x00000001015902a0 _PyRun_SimpleFileObject + 336
        48  Python                              0x000000010158f8b4 _PyRun_AnyFileObject + 200
        49  Python                              0x00000001015bb374 pymain_run_file_obj + 180
        50  Python                              0x00000001015baa50 pymain_run_file + 72
        51  Python                              0x00000001015ba0b0 pymain_run_python + 548
        52  Python                              0x00000001015b9e4c Py_RunMain + 24
        53  Python                              0x00000001015bb508 pymain_main + 36
        54  Python                              0x00000001015bb7e0 Py_BytesMain + 40
        55  dyld                                0x00000001937bc274 start + 2840
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      /usr/local/bin/python3 /Users/aalford28/Documents/Fq/eerer.py

**Comment by glyph** [comment]
@Alvin-Alford thanks for reporting this! can you give a more complete, runnable example here? there is no `Fq/eerer.py` in QuickMacHotKey.

**Comment by Alvin-Alford** [comment]
Yeah I don;t know what was happening i managed to fix it but i have another interesting error that when build into an application with py2app it has a very interesting error I provide an example soon

**Comment by Alvin-Alford** [comment]
Their is an issue with pyobjc not anything to do with your code

**Comment by glyph** [comment]
Thanks for letting me know.
